"""empty message

Revision ID: 36de547d6e94
Revises: fcd6b4a5b078
Create Date: 2026-06-10 00:03:25.656973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36de547d6e94'
down_revision = 'fcd6b4a5b078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comments')
    op.drop_table('favorites')
    op.drop_table('evento')
    op.drop_table('partido')
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_team_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('away_team_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('home_team_logo', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('away_team_logo', sa.String(length=300), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_column('away_team_logo')
        batch_op.drop_column('home_team_logo')
        batch_op.drop_column('away_team_name')
        batch_op.drop_column('home_team_name')

    op.create_table('partido',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('partido_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('liga', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('temporada', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('jornada', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('home_team', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('away_team', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('score_home', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score_away', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('hora', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('estadio', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='partido_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('evento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('jugador', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('minuto', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('partido_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['partido_id'], ['partido.id'], name=op.f('evento_partido_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('evento_pkey'))
    )
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('favorites_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('favorites_pkey'))
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.drop_table('favorite')
    op.drop_table('comment')
    # ### end Alembic commands ###
