"""empty message

Revision ID: 4c76048b3712
Revises: db56692f432d
Create Date: 2026-06-07 20:35:04.893083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c76048b3712'
down_revision = 'db56692f432d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_team_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('away_team_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('home_team_logo', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('away_team_logo', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_column('away_team_logo')
        batch_op.drop_column('home_team_logo')
        batch_op.drop_column('away_team_name')
        batch_op.drop_column('home_team_name')

    # ### end Alembic commands ###
